apiVersion: v1
kind: Secret
metadata:
  name: {{ include "practice4.fullname" . }}-db-secret
  labels:
    {{- include "practice4.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.user | quote }}
  password: {{ .Values.postgres.password | quote }}